### ISSUE TITLE
feat: register and login 

### ISSUE THREAD

**Issue by emirsoyturk** [Dijital-Twin/client#5]
### Goal
Write frontend part of register and login pages. 

### Steps
- [ ] Write UI code with responsive style
- [ ] Connect Register and Login with Backend

**Comment by t4r7k** [comment]
### Auth0 Integration for Enhanced User Authentication

In this [commit](https://github.com/Dijital-Twin/client/commit/51b7bbcb2f798a7f502d1bfa13cf3f72f3aebc03), we've integrated Auth0 to provide a comprehensive registration and login system within our client application. This upgrade enables users to easily register and log in using their existing accounts from popular services such as Google, Microsoft, and Meta, streamlining the authentication process. The implementation of Auth0 not only simplifies access but also enhances security and user experience. Below is a preview of the updated login page showcasing the seamless integration.

<img width="423" alt="Screenshot 2024-03-23 at 16 54 02" src="https://github.com/Dijital-Twin/client/assets/78061895/75d395be-d235-4ca3-8f37-ec8d1e9c03a3">

Login button is placed top right of the navigation bar:

<img width="882" alt="Screenshot 2024-03-23 at 16 58 55" src="https://github.com/Dijital-Twin/client/assets/78061895/d56fa66f-ed5c-4014-bc5f-8c6c1a7c8b0e">

After the authorization, user's profile photo and e-mail is replaced login button on the navigation bar:

<img width="843" alt="Screenshot 2024-03-23 at 17 05 19" src="https://github.com/Dijital-Twin/client/assets/78061895/4ae3f8fe-1aa7-4d37-be18-c06919d1d5ec">
